//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIHEI.SC4Buddy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string GameLocation {
            get {
                return ((string)(this["GameLocation"]));
            }
            set {
                this["GameLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("15")]
        public int AutoSaveWaitTime {
            get {
                return ((int)(this["AutoSaveWaitTime"]));
            }
            set {
                this["AutoSaveWaitTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LauncherDisableSound {
            get {
                return ((bool)(this["LauncherDisableSound"]));
            }
            set {
                this["LauncherDisableSound"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LauncherDisableMusic {
            get {
                return ((bool)(this["LauncherDisableMusic"]));
            }
            set {
                this["LauncherDisableMusic"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LauncherDisableAudio {
            get {
                return ((bool)(this["LauncherDisableAudio"]));
            }
            set {
                this["LauncherDisableAudio"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LauncherCustomResolution {
            get {
                return ((bool)(this["LauncherCustomResolution"]));
            }
            set {
                this["LauncherCustomResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LauncherRenderMode {
            get {
                return ((string)(this["LauncherRenderMode"]));
            }
            set {
                this["LauncherRenderMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LauncherResolution {
            get {
                return ((string)(this["LauncherResolution"]));
            }
            set {
                this["LauncherResolution"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Launcher32BitColourDepth {
            get {
                return ((bool)(this["Launcher32BitColourDepth"]));
            }
            set {
                this["Launcher32BitColourDepth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int LauncherCpuCount {
            get {
                return ((int)(this["LauncherCpuCount"]));
            }
            set {
                this["LauncherCpuCount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LauncherDisableExceptionHandling {
            get {
                return ((bool)(this["LauncherDisableExceptionHandling"]));
            }
            set {
                this["LauncherDisableExceptionHandling"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LauncherSkipIntro {
            get {
                return ((bool)(this["LauncherSkipIntro"]));
            }
            set {
                this["LauncherSkipIntro"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LauncherDisableBackgroundLoader {
            get {
                return ((bool)(this["LauncherDisableBackgroundLoader"]));
            }
            set {
                this["LauncherDisableBackgroundLoader"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LauncherIgnoreMissingModels {
            get {
                return ((bool)(this["LauncherIgnoreMissingModels"]));
            }
            set {
                this["LauncherIgnoreMissingModels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LauncherCursorColour {
            get {
                return ((string)(this["LauncherCursorColour"]));
            }
            set {
                this["LauncherCursorColour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LauncherWriteLog {
            get {
                return ((bool)(this["LauncherWriteLog"]));
            }
            set {
                this["LauncherWriteLog"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LauncherDisableIME {
            get {
                return ((bool)(this["LauncherDisableIME"]));
            }
            set {
                this["LauncherDisableIME"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LauncherPauseMinimized {
            get {
                return ((bool)(this["LauncherPauseMinimized"]));
            }
            set {
                this["LauncherPauseMinimized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool EnableAutoSave {
            get {
                return ((bool)(this["EnableAutoSave"]));
            }
            set {
                this["EnableAutoSave"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Wallpaper {
            get {
                return ((int)(this["Wallpaper"]));
            }
            set {
                this["Wallpaper"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LauncherCpuPriority {
            get {
                return ((string)(this["LauncherCpuPriority"]));
            }
            set {
                this["LauncherCpuPriority"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string LauncherLanguage {
            get {
                return ((string)(this["LauncherLanguage"]));
            }
            set {
                this["LauncherLanguage"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool FetchInfoFromRemote {
            get {
                return ((bool)(this["FetchInfoFromRemote"]));
            }
            set {
                this["FetchInfoFromRemote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool DeveloperUploadToRemote {
            get {
                return ((bool)(this["DeveloperUploadToRemote"]));
            }
            set {
                this["DeveloperUploadToRemote"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string UserEmail {
            get {
                return ((string)(this["UserEmail"]));
            }
            set {
                this["UserEmail"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool AllowDependencyCheck {
            get {
                return ((bool)(this["AllowDependencyCheck"]));
            }
            set {
                this["AllowDependencyCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InstallerAskToRemoveNonPluginFiles {
            get {
                return ((bool)(this["InstallerAskToRemoveNonPluginFiles"]));
            }
            set {
                this["InstallerAskToRemoveNonPluginFiles"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool InstallerAutoRunExecutables {
            get {
                return ((bool)(this["InstallerAutoRunExecutables"]));
            }
            set {
                this["InstallerAutoRunExecutables"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool InstallerAskForAdditionalInfo {
            get {
                return ((bool)(this["InstallerAskForAdditionalInfo"]));
            }
            set {
                this["InstallerAskForAdditionalInfo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool LauncherWindowMode {
            get {
                return ((bool)(this["LauncherWindowMode"]));
            }
            set {
                this["LauncherWindowMode"] = value;
            }
        }
    }
}
