// <auto-generated/>
namespace NIHEI.SC4Buddy.View.UserFolders
{
    public partial class UserFolderForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(UserFolderForm));
            this.splitContainer1 = new System.Windows.Forms.SplitContainer();
            this.installedPluginsListView = new System.Windows.Forms.ListView();
            this.pluginColumn = ((System.Windows.Forms.ColumnHeader)(new System.Windows.Forms.ColumnHeader()));
            this.groupBox1 = new System.Windows.Forms.GroupBox();
            this.moveOrCopyButton = new System.Windows.Forms.Button();
            this.panel1 = new System.Windows.Forms.Panel();
            this.descriptionRichTextBox = new System.Windows.Forms.RichTextBox();
            this.updateInfoButton = new System.Windows.Forms.Button();
            this.uninstallButton = new System.Windows.Forms.Button();
            this.linkLabel = new System.Windows.Forms.LinkLabel();
            this.label2 = new System.Windows.Forms.Label();
            this.nameLabel = new System.Windows.Forms.Label();
            this.authorLabel = new System.Windows.Forms.Label();
            this.label1 = new System.Windows.Forms.Label();
            this.closeButton = new System.Windows.Forms.Button();
            this.selectFilesToInstallDialog = new System.Windows.Forms.OpenFileDialog();
            this.menuStrip1 = new System.Windows.Forms.MenuStrip();
            this.pluginsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.installToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.scanForNewPluginsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.toolsToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.scanForNonpluginFilesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.updateInfoForAllPluginsFromServerToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.checkForMissingDependenciesToolStripMenuItem = new System.Windows.Forms.ToolStripMenuItem();
            this.button1 = new System.Windows.Forms.Button();
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).BeginInit();
            this.splitContainer1.Panel1.SuspendLayout();
            this.splitContainer1.Panel2.SuspendLayout();
            this.splitContainer1.SuspendLayout();
            this.groupBox1.SuspendLayout();
            this.panel1.SuspendLayout();
            this.menuStrip1.SuspendLayout();
            this.SuspendLayout();
            // 
            // splitContainer1
            // 
            resources.ApplyResources(this.splitContainer1, "splitContainer1");
            this.splitContainer1.Name = "splitContainer1";
            // 
            // splitContainer1.Panel1
            // 
            this.splitContainer1.Panel1.Controls.Add(this.installedPluginsListView);
            // 
            // splitContainer1.Panel2
            // 
            this.splitContainer1.Panel2.Controls.Add(this.groupBox1);
            // 
            // installedPluginsListView
            // 
            this.installedPluginsListView.Columns.AddRange(new System.Windows.Forms.ColumnHeader[] {
            this.pluginColumn});
            resources.ApplyResources(this.installedPluginsListView, "installedPluginsListView");
            this.installedPluginsListView.HeaderStyle = System.Windows.Forms.ColumnHeaderStyle.None;
            this.installedPluginsListView.MultiSelect = false;
            this.installedPluginsListView.Name = "installedPluginsListView";
            this.installedPluginsListView.UseCompatibleStateImageBehavior = false;
            this.installedPluginsListView.View = System.Windows.Forms.View.Details;
            this.installedPluginsListView.SelectedIndexChanged += new System.EventHandler(this.InstalledPluginsListViewSelectedIndexChanged);
            // 
            // pluginColumn
            // 
            resources.ApplyResources(this.pluginColumn, "pluginColumn");
            // 
            // groupBox1
            // 
            resources.ApplyResources(this.groupBox1, "groupBox1");
            this.groupBox1.Controls.Add(this.button1);
            this.groupBox1.Controls.Add(this.moveOrCopyButton);
            this.groupBox1.Controls.Add(this.panel1);
            this.groupBox1.Controls.Add(this.updateInfoButton);
            this.groupBox1.Controls.Add(this.uninstallButton);
            this.groupBox1.Controls.Add(this.linkLabel);
            this.groupBox1.Controls.Add(this.label2);
            this.groupBox1.Controls.Add(this.nameLabel);
            this.groupBox1.Controls.Add(this.authorLabel);
            this.groupBox1.Controls.Add(this.label1);
            this.groupBox1.Name = "groupBox1";
            this.groupBox1.TabStop = false;
            // 
            // moveOrCopyButton
            // 
            resources.ApplyResources(this.moveOrCopyButton, "moveOrCopyButton");
            this.moveOrCopyButton.Name = "moveOrCopyButton";
            this.moveOrCopyButton.UseVisualStyleBackColor = true;
            this.moveOrCopyButton.Click += new System.EventHandler(this.MoveOrCopyButtonClick);
            // 
            // panel1
            // 
            resources.ApplyResources(this.panel1, "panel1");
            this.panel1.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;
            this.panel1.Controls.Add(this.descriptionRichTextBox);
            this.panel1.Name = "panel1";
            // 
            // descriptionRichTextBox
            // 
            this.descriptionRichTextBox.BackColor = System.Drawing.SystemColors.Control;
            this.descriptionRichTextBox.BorderStyle = System.Windows.Forms.BorderStyle.None;
            resources.ApplyResources(this.descriptionRichTextBox, "descriptionRichTextBox");
            this.descriptionRichTextBox.Name = "descriptionRichTextBox";
            // 
            // updateInfoButton
            // 
            resources.ApplyResources(this.updateInfoButton, "updateInfoButton");
            this.updateInfoButton.Name = "updateInfoButton";
            this.updateInfoButton.UseVisualStyleBackColor = true;
            this.updateInfoButton.Click += new System.EventHandler(this.UpdateInfoButtonClick);
            // 
            // uninstallButton
            // 
            resources.ApplyResources(this.uninstallButton, "uninstallButton");
            this.uninstallButton.Name = "uninstallButton";
            this.uninstallButton.UseVisualStyleBackColor = true;
            this.uninstallButton.Click += new System.EventHandler(this.UninstallButtonClick);
            // 
            // linkLabel
            // 
            resources.ApplyResources(this.linkLabel, "linkLabel");
            this.linkLabel.Name = "linkLabel";
            this.linkLabel.TabStop = true;
            this.linkLabel.LinkClicked += new System.Windows.Forms.LinkLabelLinkClickedEventHandler(this.LinkLabelLinkClicked);
            // 
            // label2
            // 
            resources.ApplyResources(this.label2, "label2");
            this.label2.Name = "label2";
            // 
            // nameLabel
            // 
            resources.ApplyResources(this.nameLabel, "nameLabel");
            this.nameLabel.Name = "nameLabel";
            // 
            // authorLabel
            // 
            resources.ApplyResources(this.authorLabel, "authorLabel");
            this.authorLabel.Name = "authorLabel";
            // 
            // label1
            // 
            resources.ApplyResources(this.label1, "label1");
            this.label1.Name = "label1";
            // 
            // closeButton
            // 
            resources.ApplyResources(this.closeButton, "closeButton");
            this.closeButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.closeButton.Name = "closeButton";
            this.closeButton.UseVisualStyleBackColor = true;
            this.closeButton.Click += new System.EventHandler(this.CloseButtonClick);
            // 
            // selectFilesToInstallDialog
            // 
            this.selectFilesToInstallDialog.Multiselect = true;
            resources.ApplyResources(this.selectFilesToInstallDialog, "selectFilesToInstallDialog");
            // 
            // menuStrip1
            // 
            this.menuStrip1.Items.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.pluginsToolStripMenuItem,
            this.toolsToolStripMenuItem});
            resources.ApplyResources(this.menuStrip1, "menuStrip1");
            this.menuStrip1.Name = "menuStrip1";
            // 
            // pluginsToolStripMenuItem
            // 
            this.pluginsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.installToolStripMenuItem,
            this.scanForNewPluginsToolStripMenuItem});
            this.pluginsToolStripMenuItem.Name = "pluginsToolStripMenuItem";
            resources.ApplyResources(this.pluginsToolStripMenuItem, "pluginsToolStripMenuItem");
            // 
            // installToolStripMenuItem
            // 
            this.installToolStripMenuItem.Name = "installToolStripMenuItem";
            resources.ApplyResources(this.installToolStripMenuItem, "installToolStripMenuItem");
            this.installToolStripMenuItem.Click += new System.EventHandler(this.InstallToolStripMenuItemClick);
            // 
            // scanForNewPluginsToolStripMenuItem
            // 
            this.scanForNewPluginsToolStripMenuItem.Name = "scanForNewPluginsToolStripMenuItem";
            resources.ApplyResources(this.scanForNewPluginsToolStripMenuItem, "scanForNewPluginsToolStripMenuItem");
            this.scanForNewPluginsToolStripMenuItem.Click += new System.EventHandler(this.ScanForNewPluginsToolStripMenuItemClick);
            // 
            // toolsToolStripMenuItem
            // 
            this.toolsToolStripMenuItem.DropDownItems.AddRange(new System.Windows.Forms.ToolStripItem[] {
            this.scanForNonpluginFilesToolStripMenuItem,
            this.updateInfoForAllPluginsFromServerToolStripMenuItem,
            this.checkForMissingDependenciesToolStripMenuItem});
            this.toolsToolStripMenuItem.Name = "toolsToolStripMenuItem";
            resources.ApplyResources(this.toolsToolStripMenuItem, "toolsToolStripMenuItem");
            // 
            // scanForNonpluginFilesToolStripMenuItem
            // 
            this.scanForNonpluginFilesToolStripMenuItem.Name = "scanForNonpluginFilesToolStripMenuItem";
            resources.ApplyResources(this.scanForNonpluginFilesToolStripMenuItem, "scanForNonpluginFilesToolStripMenuItem");
            this.scanForNonpluginFilesToolStripMenuItem.Click += new System.EventHandler(this.ScanForNonpluginFilesToolStripMenuItemClick);
            // 
            // updateInfoForAllPluginsFromServerToolStripMenuItem
            // 
            this.updateInfoForAllPluginsFromServerToolStripMenuItem.Name = "updateInfoForAllPluginsFromServerToolStripMenuItem";
            resources.ApplyResources(this.updateInfoForAllPluginsFromServerToolStripMenuItem, "updateInfoForAllPluginsFromServerToolStripMenuItem");
            this.updateInfoForAllPluginsFromServerToolStripMenuItem.Click += new System.EventHandler(this.UpdateInfoForAllPluginsFromServerToolStripMenuItemClick);
            // 
            // checkForMissingDependenciesToolStripMenuItem
            // 
            this.checkForMissingDependenciesToolStripMenuItem.Name = "checkForMissingDependenciesToolStripMenuItem";
            resources.ApplyResources(this.checkForMissingDependenciesToolStripMenuItem, "checkForMissingDependenciesToolStripMenuItem");
            this.checkForMissingDependenciesToolStripMenuItem.Click += new System.EventHandler(this.CheckForMissingDependenciesToolStripMenuItemClick);
            // 
            // button1
            // 
            resources.ApplyResources(this.button1, "button1");
            this.button1.Name = "button1";
            this.button1.UseVisualStyleBackColor = true;
            // 
            // UserFolderForm
            // 
            resources.ApplyResources(this, "$this");
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this.closeButton;
            this.Controls.Add(this.splitContainer1);
            this.Controls.Add(this.closeButton);
            this.Controls.Add(this.menuStrip1);
            this.MainMenuStrip = this.menuStrip1;
            this.Name = "UserFolderForm";
            this.Activated += new System.EventHandler(this.UserFolderFormActivated);
            this.Load += new System.EventHandler(this.UserFolderFormLoad);
            this.splitContainer1.Panel1.ResumeLayout(false);
            this.splitContainer1.Panel2.ResumeLayout(false);
            ((System.ComponentModel.ISupportInitialize)(this.splitContainer1)).EndInit();
            this.splitContainer1.ResumeLayout(false);
            this.groupBox1.ResumeLayout(false);
            this.groupBox1.PerformLayout();
            this.panel1.ResumeLayout(false);
            this.menuStrip1.ResumeLayout(false);
            this.menuStrip1.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Button closeButton;
        private System.Windows.Forms.GroupBox groupBox1;
        private System.Windows.Forms.Label authorLabel;
        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.Button uninstallButton;
        private System.Windows.Forms.Panel panel1;
        private System.Windows.Forms.RichTextBox descriptionRichTextBox;
        private System.Windows.Forms.Label nameLabel;
        private System.Windows.Forms.ListView installedPluginsListView;
        private System.Windows.Forms.ColumnHeader pluginColumn;
        private System.Windows.Forms.OpenFileDialog selectFilesToInstallDialog;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.LinkLabel linkLabel;
        private System.Windows.Forms.Button updateInfoButton;
        private System.Windows.Forms.SplitContainer splitContainer1;
        private System.Windows.Forms.MenuStrip menuStrip1;
        private System.Windows.Forms.ToolStripMenuItem pluginsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem installToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem scanForNewPluginsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem toolsToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem scanForNonpluginFilesToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem updateInfoForAllPluginsFromServerToolStripMenuItem;
        private System.Windows.Forms.ToolStripMenuItem checkForMissingDependenciesToolStripMenuItem;
        private System.Windows.Forms.Button moveOrCopyButton;
        private System.Windows.Forms.Button button1;
    }
}