//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIHEI.SC4Buddy
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RemoteEntities : DbContext
    {
        public RemoteEntities()
            : base("name=RemoteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Author> Authors { get; set; }
        public DbSet<RemotePlugin> RemotePlugins { get; set; }
        public DbSet<RemotePluginFile> RemotePluginFiles { get; set; }
        public DbSet<User> Users { get; set; }
    }
}
