//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIHEI.SC4Buddy
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemotePluginFile
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Checksum { get; set; }
        public int PluginId { get; set; }
    
        public virtual RemotePlugin Plugin { get; set; }
    }
}
