//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIHEI.SC4Buddy
{
    using System;
    using System.Collections.Generic;
    
    public partial class RemotePlugin
    {
        public RemotePlugin()
        {
            this.Files = new HashSet<RemotePluginFile>();
            this.Dependencies = new HashSet<RemotePlugin>();
            this.DependencyFor = new HashSet<RemotePlugin>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public int AuthorId { get; set; }
        public string Description { get; set; }
        public string Link { get; set; }
    
        public virtual Author Author { get; set; }
        public virtual ICollection<RemotePluginFile> Files { get; set; }
        public virtual ICollection<RemotePlugin> Dependencies { get; set; }
        public virtual ICollection<RemotePlugin> DependencyFor { get; set; }
    }
}
