//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIHEI.SC4Buddy
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public User()
        {
            this.Authors = new HashSet<Author>();
        }
    
        public int Id { get; set; }
        public string Email { get; set; }
        public string Salt { get; set; }
        public string Rights { get; set; }
        public byte[] Passphrase { get; set; }
    
        public virtual ICollection<Author> Authors { get; set; }
    }
}
