//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NIHEI.SC4Buddy.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LocalizationStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LocalizationStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NIHEI.SC4Buddy.Localization.LocalizationStrings", typeof(LocalizationStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional permissions required..
        /// </summary>
        internal static string AdditionalPermissionsRequired {
            get {
                return ResourceManager.GetString("AdditionalPermissionsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use the same alias for multiple plugin folders and the alias cannot be blank..
        /// </summary>
        internal static string AliasError {
            get {
                return ResourceManager.GetString("AliasError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to install the selected {0} plugins?.
        /// </summary>
        internal static string AreYouSureYouWantToInstallTheSelectedPlugins {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToInstallTheSelectedPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to uninstall {0}?.
        /// </summary>
        internal static string AreYouSureYouWantToUninstall {
            get {
                return ResourceManager.GetString("AreYouSureYouWantToUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication error.
        /// </summary>
        internal static string AuthenticationError {
            get {
                return ResourceManager.GetString("AuthenticationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion of author.
        /// </summary>
        internal static string ConfirmDeletionOfAuthor {
            get {
                return ResourceManager.GetString("ConfirmDeletionOfAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm deletion of non plugin files.
        /// </summary>
        internal static string ConfirmDeletionOfNonPluginFiles {
            get {
                return ResourceManager.GetString("ConfirmDeletionOfNonPluginFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm installation.
        /// </summary>
        internal static string ConfirmInstallation {
            get {
                return ResourceManager.GetString("ConfirmInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm uninstall.
        /// </summary>
        internal static string ConfirmUninstall {
            get {
                return ResourceManager.GetString("ConfirmUninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm plugin folder deletion.
        /// </summary>
        internal static string ConfirmUserFolderDeletion {
            get {
                return ResourceManager.GetString("ConfirmUserFolderDeletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to remove the plugin folder.
        /// </summary>
        internal static string ConfirmUserFolderDeletionMessageBeforeFolderName {
            get {
                return ResourceManager.GetString("ConfirmUserFolderDeletionMessageBeforeFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default user folder.
        /// </summary>
        internal static string DefaultUserFolderName {
            get {
                return ResourceManager.GetString("DefaultUserFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to run the {0} executable? Please note that the installer has to be installed in the plugin folder {1} in order to detect filechanges, otherwise you have to rescan the plugin folders manually..
        /// </summary>
        internal static string DoYouWantToRunTheNamExecutable {
            get {
                return ResourceManager.GetString("DoYouWantToRunTheNamExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail is not valid..
        /// </summary>
        internal static string EmailIsNotValid {
            get {
                return ResourceManager.GetString("EmailIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter additional plugin information.
        /// </summary>
        internal static string EnterAdditionalPluginInformation {
            get {
                return ResourceManager.GetString("EnterAdditionalPluginInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter plugin information.
        /// </summary>
        internal static string EnterPluginInformation {
            get {
                return ResourceManager.GetString("EnterPluginInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error occured during login..
        /// </summary>
        internal static string ErrorOccuredDuringLogin {
            get {
                return ResourceManager.GetString("ErrorOccuredDuringLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable files found.
        /// </summary>
        internal static string ExecutableFilesFound {
            get {
                return ResourceManager.GetString("ExecutableFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed plugins:.
        /// </summary>
        internal static string FailedPlugins {
            get {
                return ResourceManager.GetString("FailedPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files extracted to temporary folder..
        /// </summary>
        internal static string FilesExtractedToTemporaryFolder {
            get {
                return ResourceManager.GetString("FilesExtractedToTemporaryFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files moved to plugin folder..
        /// </summary>
        internal static string FilesMovedToUserFolder {
            get {
                return ResourceManager.GetString("FilesMovedToUserFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game folder not set.
        /// </summary>
        internal static string GameFolderNotSet {
            get {
                return ResourceManager.GetString("GameFolderNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game folder.
        /// </summary>
        internal static string GameUserFolderName {
            get {
                return ResourceManager.GetString("GameUserFolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information for {0} plugins were updated..
        /// </summary>
        internal static string InformationForNumPluginsWereUpdated {
            get {
                return ResourceManager.GetString("InformationForNumPluginsWereUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installation completed..
        /// </summary>
        internal static string InstallationCompleted {
            get {
                return ResourceManager.GetString("InstallationCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing plugin {0}.
        /// </summary>
        internal static string InstallingPluginNam {
            get {
                return ResourceManager.GetString("InstallingPluginNam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials..
        /// </summary>
        internal static string InvalidCredentials {
            get {
                return ResourceManager.GetString("InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game location folder is invalid. You must select the root folder (i.e. &quot;C:\Program Files (x86)\Maxis\SimCity 4&quot;).
        /// </summary>
        internal static string InvalidGameLocationFolder {
            get {
                return ResourceManager.GetString("InvalidGameLocationFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It seems like the installation did not start. If it did start then DO NOT CLOSE THIS DIALOG untill the installation is complete..
        /// </summary>
        internal static string ItSeemsLikeTheInstallationDidNotStart {
            get {
                return ResourceManager.GetString("ItSeemsLikeTheInstallationDidNotStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logged in as {0}.
        /// </summary>
        internal static string LoggedInAs {
            get {
                return ResourceManager.GetString("LoggedInAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No authors defined..
        /// </summary>
        internal static string NoAuthorsDefined {
            get {
                return ResourceManager.GetString("NoAuthorsDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file changes detected.
        /// </summary>
        internal static string NoFileChangesDetected {
            get {
                return ResourceManager.GetString("NoFileChangesDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No internet connection detected.
        /// </summary>
        internal static string NoInternetDetectionDetected {
            get {
                return ResourceManager.GetString("NoInternetDetectionDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new, deleted or updated files detected..
        /// </summary>
        internal static string NoNewDeletedOrUpdatedFilesDetected {
            get {
                return ResourceManager.GetString("NoNewDeletedOrUpdatedFilesDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non-plugin files deleted.
        /// </summary>
        internal static string NonPluginFilesDeleted {
            get {
                return ResourceManager.GetString("NonPluginFilesDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No user is logged in..
        /// </summary>
        internal static string NoUserIsLoggedIn {
            get {
                return ResourceManager.GetString("NoUserIsLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} files and {1} folders were removed..
        /// </summary>
        internal static string NumFilesAndNumFoldersWereRemoved {
            get {
                return ResourceManager.GetString("NumFilesAndNumFoldersWereRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        internal static string NumMinutes {
            get {
                return ResourceManager.GetString("NumMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} plugins failed installation. Please review these manually as some files may not have been removed correctly during recovery..
        /// </summary>
        internal static string NumPluginsFailedInstallationPleaseReview {
            get {
                return ResourceManager.GetString("NumPluginsFailedInstallationPleaseReview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} plugins installed successfully..
        /// </summary>
        internal static string NumPluginsInstalledSuccessfully {
            get {
                return ResourceManager.GetString("NumPluginsInstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords does not match..
        /// </summary>
        internal static string PasswordsDoesNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoesNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot use the same path for multiple plugin folders, the path cannot be blank, you cannot add the main plugin folder in the game folder, and the path must exist on your machine..
        /// </summary>
        internal static string PathError {
            get {
                return ResourceManager.GetString("PathError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin information stored.
        /// </summary>
        internal static string PluginInformationStored {
            get {
                return ResourceManager.GetString("PluginInformationStored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin information updated.
        /// </summary>
        internal static string PluginInformationUpdated {
            get {
                return ResourceManager.GetString("PluginInformationUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin installed successfully..
        /// </summary>
        internal static string PluginInstalledSuccessfully {
            get {
                return ResourceManager.GetString("PluginInstalledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plugin install failed..
        /// </summary>
        internal static string PluginInstallFailed {
            get {
                return ResourceManager.GetString("PluginInstallFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Possible error detected..
        /// </summary>
        internal static string PossibleErrorDetected {
            get {
                return ResourceManager.GetString("PossibleErrorDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration error.
        /// </summary>
        internal static string RegistrationError {
            get {
                return ResourceManager.GetString("RegistrationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove non-plugin files.
        /// </summary>
        internal static string RemoveNonPluginFiles {
            get {
                return ResourceManager.GetString("RemoveNonPluginFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run executable?.
        /// </summary>
        internal static string RunExecutable {
            get {
                return ResourceManager.GetString("RunExecutable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (Click browse to select the games folder).
        /// </summary>
        internal static string SelectGameLocation {
            get {
                return ResourceManager.GetString("SelectGameLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site URL help.
        /// </summary>
        internal static string SiteUrlHelp {
            get {
                return ResourceManager.GetString("SiteUrlHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The URL to the website where you have uploaded your content. (Enter only 1 URL, you can add more sites when your user has been created).
        /// </summary>
        internal static string SiteUrlHelpText {
            get {
                return ResourceManager.GetString("SiteUrlHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        internal static string StartingGame {
            get {
                return ResourceManager.GetString("StartingGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file {0} is not recognized as a supported archive. Extract the files and add them manually..
        /// </summary>
        internal static string TheFileNamIsNotRecognizedAsASupportedArchive {
            get {
                return ResourceManager.GetString("TheFileNamIsNotRecognizedAsASupportedArchive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The first time you run this program you must run it as an administrator (Right click on the shortcut and select &quot;Run as administrator&quot; and click &quot;Yes&quot; or &quot;OK&quot; in the following popup box). From there on you can start it without administrator rights..
        /// </summary>
        internal static string TheFirstTimeYouRunThisProgramYouMustRunItAsAnAdministrator {
            get {
                return ResourceManager.GetString("TheFirstTimeYouRunThisProgramYouMustRunItAsAnAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The plugin did not contain any valid files to install. {0}.
        /// </summary>
        internal static string ThePluginDigNotContainAnyValidFilesToInstall {
            get {
                return ResourceManager.GetString("ThePluginDigNotContainAnyValidFilesToInstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The site URL is invalid. Enter it in the format &quot;http://www.example.com&quot;..
        /// </summary>
        internal static string TheSiteUrlIsInvalid {
            get {
                return ResourceManager.GetString("TheSiteUrlIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This author has no associated plugins. Are you sure you want to delete this user?.
        /// </summary>
        internal static string ThisAuthorHasNoAssociatedPlugins {
            get {
                return ResourceManager.GetString("ThisAuthorHasNoAssociatedPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This author is already claimed by another user..
        /// </summary>
        internal static string ThisAuthorIsAlreadyClaimedByAnotherUser {
            get {
                return ResourceManager.GetString("ThisAuthorIsAlreadyClaimedByAnotherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This form contains {0} executable files..
        /// </summary>
        internal static string ThisFormContainsNumExecutableFiles {
            get {
                return ResourceManager.GetString("ThisFormContainsNumExecutableFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This tool will scan for all non-plugin files and empty folders and remove them from the plugin directory. Are you sure you want to proceed? (Files are moved to the recycle bin).
        /// </summary>
        internal static string ThisToolWillScanForAllNonPluginFilesAndRemoveThem {
            get {
                return ResourceManager.GetString("ThisToolWillScanForAllNonPluginFilesAndRemoveThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This author has {0} plugins in the central database. Deleting the author will NOT delete this information. Users will still be able to search for these plugins. Are you sure you want to delete this user?.
        /// </summary>
        internal static string ThisUserHasNumPluginsInTheCentralDatabase {
            get {
                return ResourceManager.GetString("ThisUserHasNumPluginsInTheCentralDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will remove {0} files and at least {1} folders (more folders may be found after the files have been deleted). Are you sure you want to continue?.
        /// </summary>
        internal static string ThisWillRemoveNumFilesAndAtLeastNumFolders {
            get {
                return ResourceManager.GetString("ThisWillRemoveNumFilesAndAtLeastNumFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to log you into the system. .
        /// </summary>
        internal static string UnableToLogYouIntoTheSystem {
            get {
                return ResourceManager.GetString("UnableToLogYouIntoTheSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file type.
        /// </summary>
        internal static string UnsupportedFileType {
            get {
                return ResourceManager.GetString("UnsupportedFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created.
        /// </summary>
        internal static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder or the content is not deleted from your computer.
        /// </summary>
        internal static string UserFolderContentIsNotDeleted {
            get {
                return ResourceManager.GetString("UserFolderContentIsNotDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has been created. You can now log in..
        /// </summary>
        internal static string UserHasBeenCreatedYouCanNowLogIn {
            get {
                return ResourceManager.GetString("UserHasBeenCreatedYouCanNowLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username help.
        /// </summary>
        internal static string UsernameHelp {
            get {
                return ResourceManager.GetString("UsernameHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your username (what others see and search after) on the site you entered above..
        /// </summary>
        internal static string UsernameHelpText {
            get {
                return ResourceManager.GetString("UsernameHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation error.
        /// </summary>
        internal static string ValidationError {
            get {
                return ResourceManager.GetString("ValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to enter additional details for the installed plugins (like name, group, description, download link etc?)? You can always do this later if you so desire..
        /// </summary>
        internal static string WouldYouLikeToEnterAdditionalDetailsForTheInstalledPlugins {
            get {
                return ResourceManager.GetString("WouldYouLikeToEnterAdditionalDetailsForTheInstalledPlugins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to enter information about the plugin?.
        /// </summary>
        internal static string WouldYouLikeToEnterInformationAboutThePlugin {
            get {
                return ResourceManager.GetString("WouldYouLikeToEnterInformationAboutThePlugin", resourceCulture);
            }
        }
        
        /// <summary>
<<<<<<< Updated upstream
=======
        ///   Looks up a localized string similar to You cannot add archives with executable installers in them. You have to add the files individually..
        /// </summary>
        internal static string YouCannotAddArchivesWithExecutableInstallersInThem {
            get {
                return ResourceManager.GetString("YouCannotAddArchivesWithExecutableInstallersInThem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot specify an empty site..
        /// </summary>
        internal static string YouCannotSpecifyAnEmptySite {
            get {
                return ResourceManager.GetString("YouCannotSpecifyAnEmptySite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot specify an empty username..
        /// </summary>
        internal static string YouCannotSpecifyAnEmptyUsername {
            get {
                return ResourceManager.GetString("YouCannotSpecifyAnEmptyUsername", resourceCulture);
            }
        }
        
        /// <summary>
>>>>>>> Stashed changes
        ///   Looks up a localized string similar to You do not appear to be connected to the internet. If this is not the case you can still try to login..
        /// </summary>
        internal static string YouDoNotAppearToBeConnectedToTheInternet {
            get {
                return ResourceManager.GetString("YouDoNotAppearToBeConnectedToTheInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must set the game location before you can use this application..
        /// </summary>
        internal static string YouMustSettheGameLocationBeforeYouCanUseThisApplication {
            get {
                return ResourceManager.GetString("YouMustSettheGameLocationBeforeYouCanUseThisApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to add at least one author in order to add plugin information to the central database..
        /// </summary>
        internal static string YouNeedToAddAtLeastOneAuthorInOrderToAddPluginInformationToTheCentralDatabase {
            get {
                return ResourceManager.GetString("YouNeedToAddAtLeastOneAuthorInOrderToAddPluginInformationToTheCentralDatabase", resourceCulture);
            }
        }
    }
}
