// <auto-generated />
namespace NIHEI.SC4Buddy.View.Author
{
    partial class SelectInstalledPluginForm
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(SelectInstalledPluginForm));
            this.label1 = new System.Windows.Forms.Label();
            this.userFolderComboBox = new System.Windows.Forms.ComboBox();
            this.pluginComboBox = new System.Windows.Forms.ComboBox();
            this.label2 = new System.Windows.Forms.Label();
            this.includeInformationCheckBox = new System.Windows.Forms.CheckBox();
            this.okButton = new System.Windows.Forms.Button();
            this.cancelButton = new System.Windows.Forms.Button();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Location = new System.Drawing.Point(12, 15);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(58, 13);
            this.label1.TabIndex = 0;
            this.label1.Text = "User folder";
            // 
            // userFolderComboBox
            // 
            this.userFolderComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.userFolderComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.userFolderComboBox.FormattingEnabled = true;
            this.userFolderComboBox.Location = new System.Drawing.Point(76, 12);
            this.userFolderComboBox.Name = "userFolderComboBox";
            this.userFolderComboBox.Size = new System.Drawing.Size(339, 21);
            this.userFolderComboBox.TabIndex = 1;
            this.userFolderComboBox.SelectedIndexChanged += new System.EventHandler(this.UserFolderComboBoxSelectedIndexChanged);
            // 
            // pluginComboBox
            // 
            this.pluginComboBox.Anchor = ((System.Windows.Forms.AnchorStyles)(((System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left) 
            | System.Windows.Forms.AnchorStyles.Right)));
            this.pluginComboBox.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.pluginComboBox.FormattingEnabled = true;
            this.pluginComboBox.Location = new System.Drawing.Point(76, 39);
            this.pluginComboBox.Name = "pluginComboBox";
            this.pluginComboBox.Size = new System.Drawing.Size(339, 21);
            this.pluginComboBox.TabIndex = 2;
            this.pluginComboBox.SelectedIndexChanged += new System.EventHandler(this.PluginComboBoxSelectedIndexChanged);
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(12, 42);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(36, 13);
            this.label2.TabIndex = 3;
            this.label2.Text = "Plugin";
            // 
            // includeInformationCheckBox
            // 
            this.includeInformationCheckBox.AutoSize = true;
            this.includeInformationCheckBox.Checked = true;
            this.includeInformationCheckBox.CheckState = System.Windows.Forms.CheckState.Checked;
            this.includeInformationCheckBox.Enabled = false;
            this.includeInformationCheckBox.Location = new System.Drawing.Point(12, 70);
            this.includeInformationCheckBox.Name = "includeInformationCheckBox";
            this.includeInformationCheckBox.Size = new System.Drawing.Size(154, 17);
            this.includeInformationCheckBox.TabIndex = 4;
            this.includeInformationCheckBox.Text = "Include entered information";
            this.includeInformationCheckBox.UseVisualStyleBackColor = true;
            this.includeInformationCheckBox.CheckedChanged += new System.EventHandler(this.IncludeInformationCheckBoxCheckedChanged);
            // 
            // okButton
            // 
            this.okButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.okButton.DialogResult = System.Windows.Forms.DialogResult.OK;
            this.okButton.Enabled = false;
            this.okButton.Location = new System.Drawing.Point(259, 66);
            this.okButton.Name = "okButton";
            this.okButton.Size = new System.Drawing.Size(75, 23);
            this.okButton.TabIndex = 5;
            this.okButton.Text = "OK";
            this.okButton.UseVisualStyleBackColor = true;
            this.okButton.Click += new System.EventHandler(this.OkButtonClick);
            // 
            // cancelButton
            // 
            this.cancelButton.Anchor = ((System.Windows.Forms.AnchorStyles)((System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Right)));
            this.cancelButton.DialogResult = System.Windows.Forms.DialogResult.Cancel;
            this.cancelButton.Location = new System.Drawing.Point(340, 66);
            this.cancelButton.Name = "cancelButton";
            this.cancelButton.Size = new System.Drawing.Size(75, 23);
            this.cancelButton.TabIndex = 6;
            this.cancelButton.Text = "Cancel";
            this.cancelButton.UseVisualStyleBackColor = true;
            this.cancelButton.Click += new System.EventHandler(this.CancelButtonClick);
            // 
            // SelectInstalledPluginForm
            // 
            this.AcceptButton = this.okButton;
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.CancelButton = this.cancelButton;
            this.ClientSize = new System.Drawing.Size(427, 101);
            this.Controls.Add(this.cancelButton);
            this.Controls.Add(this.okButton);
            this.Controls.Add(this.includeInformationCheckBox);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.pluginComboBox);
            this.Controls.Add(this.userFolderComboBox);
            this.Controls.Add(this.label1);
            this.Icon = ((System.Drawing.Icon)(resources.GetObject("$this.Icon")));
            this.Name = "SelectInstalledPluginForm";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Select installed plugin";
            this.Load += new System.EventHandler(this.SelectInstalledPluginFormLoad);
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Label label1;
        private System.Windows.Forms.ComboBox userFolderComboBox;
        private System.Windows.Forms.ComboBox pluginComboBox;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.CheckBox includeInformationCheckBox;
        private System.Windows.Forms.Button okButton;
        private System.Windows.Forms.Button cancelButton;
    }
}